# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdevNew',
                'doc_host': 'https://LuisESuarezA.github.io',
                'git_url': 'https://github.com/LuisESuarezA/nbdevNew',
                'lib_path': 'nbdevNew'},
  'syms': { 'nbdevNew.core': {'nbdevNew.core.foo': ('core.html#foo', 'nbdevNew/core.py')},
            'nbdevNew.tarea': { 'nbdevNew.tarea.Tarea': ('tarea.html#tarea', 'nbdevNew/tarea.py'),
                                'nbdevNew.tarea.Tarea.__init__': ('tarea.html#tarea.__init__', 'nbdevNew/tarea.py'),
                                'nbdevNew.tarea.Tarea.__str__': ('tarea.html#tarea.__str__', 'nbdevNew/tarea.py')}}}
