# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_tarea.ipynb.

# %% auto 0
__all__ = ['Tarea']

# %% ../nbs/01_tarea.ipynb 3
class Tarea:
    def __init__(self,
                 titulo:str, # titulo de la tarea
                 fecha_entrega:str, # fecha de entrega formato dd/mm/aaaa
                 descripcion:str='', # informacion adicional sobre la tarea
                 ) -> None:
        self.titulo = titulo
        self.fecha_entrega = fecha_entrega
        self.descripcion = descripcion
        self.completada
        self.completado= False

    def __str__(self) -> str:
        return f"Tarea: '{self.titulo}. Fecha de entrega: {self.fecha_entrega}. Completada: {self.completada}'"
    __repr__ = __str__
